version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    enabled: false
  similar-code:
    config:
      threshold: 128
  identical-code:
    config:
      threshold: 128

exclude_patterns:
  - docs/*
  - packages/grid_control/backends/htcondor_wms/*
  - packages/grid_control_cms/DashboardAPI/*
  - packages/grid_control_cms/Lexicon.py
  - packages/grid_control_cms/share/fragmentForCMSSW.py
  - packages/grid_control_gui/xmpp/*
  - packages/python_compat_json.py
  - packages/python_compat_tarfile.py
  - packages/python_compat_urllib2.py
  - packages/requests/*
